### ISSUE TITLE
I Really Like This Idea!

### ISSUE THREAD

**Issue by zicklag** [NQNStudios/hank#9]
Hi, I just wanted to mention that I really like this idea. I actually found Ink because I'm following someone who starred Hank ( thanks @sh-dave :wink: ).

I really like the Ink concept in general and think it would be awesome to be able to use it in Haxe games, particularly [Armory3D](http://http://armory3d.org/) games.

**Comment by NQNStudios** [comment]
Thank you! That's such an uplifting compliment. I appreciate it.

This project started because I want to have all the cross-platform publishing abilities of core Ink but without being stuck with Unity. I develop on Linux so I just want to be able to use VS Code for my gamedev.

I was going to try to resuscitate [Inkhaxe](https://GitHub.com/glidias/inkhaxe) but it proved very overwhelming to try and solo maintain a full Ink port. Then when I discovered hscript I realized there was a clever way to do almost everything Ink does, but only relying on existing Haxe libraries and features.

I want to disclaim that I can't guarantee I'll ever make this production ready, but my current goal is indeed to ship commercial games with it, so maybe investing your time in this won't be wasted. :)

**Comment by sh-dave** [comment]
👀 wrong mention, who is that imposter 😛 

You aren't stuck with unity as inkhaxe is just a runtime. I did some prototyping with some [Kha](https://github.com/Kode/Kha.git) g2 based drawing and that work pretty good.

But there is a lot of stuff that could be better implemented with your hscript based approach i guess. Like logic / scripting seems very cumbersome in ink. Also translating stories without repeating all the logic seems pretty much impossible there. So as zicklag already said, i also think a better integrated haxe implementation is something cool to have and i'll keep an eye on this as well.

**Comment by NQNStudios** [comment]
> You aren't stuck with unity as inkhaxe is just a runtime.
Right, that's why I was considering Inkhaxe as an alternative to the C# version. The problem with that is it's out of date and unmaintained currently.
